main:
  - weight: 1
    name: Stories
    url: /stories/
    title: My amazing Stories
    params:
      # icon: fa-solid fa-book-atlas
      icon: fa-solid fa-map-location
  - weight: 2
    identifier: guides
    name: Guides
    url: /guides/
    title: My Travel Guides
    params:
      icon: fa-solid fa-brain
  - weight: 3
    identifier: tags
    name: Tags
    url: /tags/
    title: ""
  - weight: 4
    identifier: categories
    name: Categories
    url: /categories/
    title: ""
  - weight: 5
    identifier: xhs
    pre: >
      <i><img src="/xhs.png" alt="XHS" style="display: block;  width: 50px; height: 50px;"></i>
    name: 
    url: /xhs/
    title: XiaoHongShu blog posts
